name: Backend CI

on:
  push:
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run Deno Lint
        run: deno task lint
        working-directory: supabase/functions/


    
