
name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build Frontend
        run: docker compose build frontend
      - name: Lint Frontend
        run: docker compose run frontend npm run lint
      - name: Stop and remove containers
        if: always()
        run: docker compose down
    
         

         
